// Antigravity (agy) live-quota integration.
//
// agy has no local file or public API that carries its remaining quota — the
// numbers only exist in the CLI's memory and are rendered by the interactive
// `/usage` command. BUT agy (like Claude Code) has a **statusLine hook**: it
// pipes the live session-state JSON — including a `quota` map of
// per-model-pool `{remaining_fraction, reset_time, reset_in_seconds}` — to a
// user-configured command's stdin on every render.
//
// So, opt-in, we register a tiny hook as agy's statusLine command that mirrors
// that JSON to `~/.tokenstats/agy_status.json`. Whenever the user actually runs
// agy, the mirror refreshes for free (no OAuth, no spawning agy, no quota
// spent — it piggybacks on real usage). `agyResetWindows()` reads the mirror
// and hands the numbers to the same live-window pipeline Codex/Cursor use.
//
// This is the ONE place that edits another tool's config, always user-initiated
// via the Settings toggle, reversible, and it never clobbers a statusLine the
// user set themselves.

import os from 'node:os'
import path from 'node:path'
import fs from 'node:fs'

const home = os.homedir()

// agy's own settings file (holds the statusLine config).
const AGY_SETTINGS = path.join(home, '.gemini', 'antigravity-cli', 'settings.json')
// Our files live under TokenStats' config dir.
const TOKENSTATS_DIR = path.join(home, '.tokenstats')
const HOOK_PATH = path.join(TOKENSTATS_DIR, 'agyStatusHook.cjs')
export const AGY_MIRROR_PATH = path.join(TOKENSTATS_DIR, 'agy_status.json')

// Forward-slash form so the path is safe inside both the JS hook source and the
// quoted shell command agy runs (agy passes `command` to a shell).
const fwd = (p) => p.replace(/\\/g, '/')
// The exact statusLine command we install; used verbatim to detect "is ours".
const OUR_COMMAND = `node "${fwd(HOOK_PATH)}"`

// The hook script agy executes. Reads the piped session JSON from stdin,
// mirrors it to AGY_MIRROR_PATH, and prints a compact status line back so the
// user still gets a useful agy status bar (model · context% · gemini quota%).
// Dependency-free (only `fs`); runs under the system `node` agy invokes.
const HOOK_SRC = `// Auto-generated by TokenStats — mirrors agy's live session/quota JSON.
// Managed by the "Antigravity live quota" toggle in TokenStats Settings.
const fs = require('fs')
const MIRROR = ${JSON.stringify(fwd(AGY_MIRROR_PATH))}
let raw = ''
try { raw = fs.readFileSync(0, 'utf8') } catch (e) {}
try { if (raw && raw.trim()) fs.writeFileSync(MIRROR, raw) } catch (e) {}
try {
  const d = JSON.parse(raw)
  const parts = []
  if (d.model && d.model.display_name) parts.push(d.model.display_name)
  const cw = d.context_window
  if (cw && typeof cw.used_percentage === 'number') parts.push('ctx ' + Math.round(cw.used_percentage) + '%')
  if (d.quota) {
    const fr = Object.keys(d.quota)
      .filter((k) => /^gemini/i.test(k))
      .map((k) => d.quota[k] && d.quota[k].remaining_fraction)
      .filter((x) => typeof x === 'number')
    if (fr.length) parts.push('gemini ' + Math.round(Math.min.apply(null, fr) * 100) + '%')
  }
  process.stdout.write(parts.join('  |  ') || 'agy')
} catch (e) {
  process.stdout.write('agy')
}
`

function readAgySettings() {
  try {
    return JSON.parse(fs.readFileSync(AGY_SETTINGS, 'utf8'))
  } catch {
    return null
  }
}

function writeAgySettings(cfg) {
  fs.writeFileSync(AGY_SETTINGS, JSON.stringify(cfg, null, 2))
}

function writeHookFile() {
  fs.mkdirSync(TOKENSTATS_DIR, { recursive: true })
  fs.writeFileSync(HOOK_PATH, HOOK_SRC)
}

// Current state of the integration, for the Settings toggle:
//   agyFound  — agy's settings.json exists (agy CLI is installed & initialized)
//   enabled   — our hook is the active statusLine command
//   foreign   — a DIFFERENT (user's own) statusLine command is set; we won't touch it
//   mirrorAgeMs — how long since the mirror last refreshed (null = never)
export function getAgyQuotaState() {
  const cfg = readAgySettings()
  if (!cfg) return { agyFound: false, enabled: false, foreign: false, mirrorAgeMs: null }
  const cmd = (cfg.statusLine && cfg.statusLine.command) || ''
  const enabled = cmd === OUR_COMMAND
  let mirrorAgeMs = null
  try {
    mirrorAgeMs = Date.now() - fs.statSync(AGY_MIRROR_PATH).mtimeMs
  } catch {
    // mirror not written yet
  }
  return { agyFound: true, enabled, foreign: !!cmd && !enabled, mirrorAgeMs }
}

// Install our hook as agy's statusLine command. Refuses (ok:false) if agy isn't
// set up, or if the user already has their own statusLine command — we never
// overwrite a foreign one.
export function enableAgyQuota() {
  const cfg = readAgySettings()
  if (!cfg) return { ok: false, reason: 'notfound' }
  const cur = (cfg.statusLine && cfg.statusLine.command) || ''
  if (cur && cur !== OUR_COMMAND) return { ok: false, reason: 'foreign' }
  writeHookFile()
  cfg.statusLine = { type: 'command', command: OUR_COMMAND, enabled: true }
  try {
    writeAgySettings(cfg)
  } catch {
    return { ok: false, reason: 'write' }
  }
  return { ok: true, ...getAgyQuotaState() }
}

// Remove our hook (only if it's still ours — never disturb a user's own).
export function disableAgyQuota() {
  const cfg = readAgySettings()
  if (!cfg) return { ok: true }
  const cur = (cfg.statusLine && cfg.statusLine.command) || ''
  if (cur === OUR_COMMAND) {
    cfg.statusLine = { type: 'command', command: '', enabled: true }
    try {
      writeAgySettings(cfg)
    } catch {
      return { ok: false, reason: 'write' }
    }
  }
  return { ok: true, ...getAgyQuotaState() }
}

// Re-assert the hook file on startup if the integration is enabled (the temp/
// config dir could have been cleared, or agy re-initialized). Cheap no-op
// otherwise. Never enables on its own.
export function ensureAgyHook() {
  try {
    if (getAgyQuotaState().enabled && !fs.existsSync(HOOK_PATH)) writeHookFile()
  } catch {
    // best-effort
  }
}

// Live quota windows for agy, in the shape mergeLiveLimits/toLiveWindow expect
// (same as codexResetWindows). We surface the **Gemini** pools (the user's
// Gemini subscription) as a single weekly window driven by the most-consumed
// pool — the binding number that actually matters. Returns [] if the mirror is
// missing or carries no gemini quota.
export function agyResetWindows() {
  let d
  try {
    d = JSON.parse(fs.readFileSync(AGY_MIRROR_PATH, 'utf8'))
  } catch {
    return []
  }
  const q = d && d.quota
  if (!q) return []
  let worst = null
  for (const [k, v] of Object.entries(q)) {
    if (!/^gemini/i.test(k)) continue
    if (!v || typeof v.remaining_fraction !== 'number') continue
    if (!worst || v.remaining_fraction < worst.remaining_fraction) worst = v
  }
  if (!worst) return []
  const used = Math.max(0, Math.min(100, (1 - worst.remaining_fraction) * 100))
  const resetsAt = worst.reset_time
    ? Date.parse(worst.reset_time)
    : typeof worst.reset_in_seconds === 'number'
      ? Date.now() + worst.reset_in_seconds * 1000
      : null
  return [
    {
      label: 'weekly', // agy's gemini quota is a ~7-day window
      windowMinutes: 7 * 24 * 60,
      usedPercent: used,
      remainingPercent: Math.max(0, 100 - used),
      resetsAt: Number.isFinite(resetsAt) ? resetsAt : null,
    },
  ]
}
